### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by edrex**
This sounds hopeful but is a dead end. Be upfront about that.

Scrapping mobile is the only option to get contact info.

### CODE REVIEW

**Comment by alextousss** [comment]
What you say is false. 

Have you taken the time to understand what this repo is about and how it works?

The goal is to parse .html files from Facebook's archive to get your contact's phone numbers and export them to the vCard format. 

I just tried it, and it still works as it did two years ago when I created it.

**Comment by edrex** [comment]
Yes, I understand the intention of your script and have read it.

Did you read the text of my PR? My experience is that the facebook html export only contains contact **name** and, if contact has specifically enabled the export email setting, **email**, in friends/friends.html. Also this file doesn't have a table structure, it's just divs.

Which file in the export are you running your script on? Are you sure you're using an up-to-date export?

**Comment by edrex** [comment]
Maybe you have a different output from the API than I do, but the text as it stands is misleading. It seems irresponsible to continue to publish incomplete/outdated information that others will waste time following with no benefit. But it's your project so I won't say more. Good day.

**Comment by alextousss** [comment]
Hello,

I don't know whether Facebook changed the format of the archive. But I downloaded mine a week ago, and it contained phone numbers of my contacts. The script can work.

If it doesn't, feel free to make a pull request with a fix.

**Pull request closed without merging**
